export enum FILTER_ACTIONS {
  CLEAR_FILTER = 'CLEAR_FILTER',
  SET_FILTER = 'SET_FILTER',
  TOGGLE_FILTER_MENU = 'TOGGLE_FILTER_MENU',
  START_FILTERING = 'START_FILTERING',
  STOP_FILTERING = 'STOP_FILTERING',
  REMOVE_ONE = 'REMOVE_ONE',
}